services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8008:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/code
    depends_on:
      - php
    working_dir: /code/public

  php:
    image: php:8.3-fpm
    volumes:
      - ./:/code
    working_dir: /code

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Définit le mot de passe root pour MySQL
      MYSQL_DATABASE: blog # Nom de la base de données à créer
      MYSQL_USER: randy_rt # Nom d'utilisateur pour l'accès à la base de données
      MYSQL_PASSWORD: user_password # Mot de passe pour l'utilisateur
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
