services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8008:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/code
    depends_on:
      - php
    working_dir: /code/public

  php:
    image: php:8.3-fpm
    volumes:
      - ./:/code
    working_dir: /code

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: chinese_services_plateform
      MYSQL_ROOT_PASSWORD: "new_password"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
